version: '3.8'

services:
  # Nginx service for reverse proxy
  nginx:
    image: nginx:alpine
    container_name: connect-aid-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - connect-aid-network

  # Backend service
  backend:
    build:
      context: ./backEnd
      dockerfile: Dockerfile
    container_name: connect-aid-backend
    ports:
      - "5000:5000"
    volumes:
      - uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=5000
      - CURRENT_HOST=18.206.159.67
      - FRONTEND_PORT=80
      - ADDITIONAL_ORIGINS=http://18.206.159.67,http://18.206.159.67:80,http://nginx,http://nginx:80
      - MONGO_URI=mongodb+srv://root:12345@connectaid-cluster.yv9ci.mongodb.net/?retryWrites=true&w=majority&appName=ConnectAid-Cluster
      - JWT_SECRET=9b773c7c41a6c77042443a60c24477af6003c6108422540d99ddd04f23ed26206a7739d50586227e8066b8894d112d00a1557438b442815bc3c246cd7b8e7c95
      - JWT_EXPIRE=24h
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://backend:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    networks:
      - connect-aid-network

  # Frontend service
  frontend:
    build:
      context: ./frontEnd
      dockerfile: Dockerfile
    container_name: connect-aid-frontend
    environment:
      - NODE_ENV=production
      - VITE_API_URL=/api
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://frontend:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - connect-aid-network

  # Selenium E2E Tests (runs on demand)
  selenium-tests:
    build:
      context: ./tests/selenium
      dockerfile: Dockerfile
    container_name: connect-aid-selenium-tests
    environment:
      - NODE_ENV=test
      - CI=true
      - TEST_BASE_URL=http://nginx:80
    volumes:
      - ./tests/selenium/test-results:/app/test-results
      - ./tests/selenium/screenshots:/app/screenshots
    depends_on:
      nginx:
        condition: service_started
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
    networks:
      - connect-aid-network
    profiles:
      - testing
    command: ["./run-tests.sh"]

networks:
  connect-aid-network:
    driver: bridge

volumes:
  uploads:
    driver: local
