version: '3.8'

services:
  # Nginx service for reverse proxy
  nginx:
    image: nginx:alpine
    container_name: connect-aid-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - connect-aid-network

  # Backend service
  backend:
    build:
      context: ./backEnd
      dockerfile: Dockerfile
    container_name: connect-aid-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backEnd:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb+srv://root:12345@connectaid-cluster.yv9ci.mongodb.net/?retryWrites=true&w=majority&appName=ConnectAid-Cluster
      - JWT_SECRET=9b773c7c41a6c77042443a60c24477af6003c6108422540d99ddd04f23ed26206a7739d50586227e8066b8894d112d00a1557438b442815bc3c246cd7b8e7c95
      - JWT_EXPIRE=24h
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://backend:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  # Frontend service
  frontend:
    build:
      context: ./frontEnd
      dockerfile: Dockerfile
    container_name: connect-aid-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontEnd:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://backend:5000
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://frontend:5173"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Selenium test service
  selenium:
    image: selenium/standalone-chrome:latest
    container_name: connect-aid-selenium
    shm_size: '2gb'
    environment:
      - SE_NODE_MAX_SESSIONS=4
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    ports:
      - "4444:4444"
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

  # Test runner service
  test-runner:
    build:
      context: ./tests/selenium
      dockerfile: Dockerfile
    container_name: connect-aid-test-runner
    volumes:
      - ./tests/selenium:/app
      - ./test-results:/app/test-results
    environment:
      - TEST_BASE_URL=http://nginx
      - CI=true
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
      selenium:
        condition: service_started
    command: npm test

volumes:
  mongodb_data:

networks:
  connect-aid-network:
    driver: bridge
