version: '3.8'

services:
  # Nginx service for reverse proxy
  nginx:
    image: nginx:latest
    container_name: connect-aid-nginx
    restart: unless-stopped
    ports:
      - "${NGINX_PORT:-80}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - connect-aid-network

  # Backend service
  backend:
    build:
      context: ./backEnd
      dockerfile: Dockerfile
    container_name: connect-aid-backend
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT:-5000}:5000"
    env_file:
      - ./backEnd/.env
    environment:
      - CURRENT_HOST=${DOMAIN_NAME:-localhost}
      - FRONTEND_PORT=${FRONTEND_PORT:-5173}
      - ADDITIONAL_ORIGINS=${ADDITIONAL_ORIGINS:-}
    volumes:
      - ./backEnd:/app
      - /app/node_modules
      - ./backEnd/uploads:/app/uploads
    networks:
      - connect-aid-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:${BACKEND_PORT:-5000}/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  # Frontend service
  frontend:
    build:
      context: ./frontEnd
      dockerfile: Dockerfile
    container_name: connect-aid-frontend
    restart: unless-stopped
    expose:
      - "${FRONTEND_PORT:-5173}"
    env_file:
      - ./frontEnd/.env
    environment:
      - VITE_CURRENT_HOST=${DOMAIN_NAME:-localhost}
    volumes:
      - ./frontEnd:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - connect-aid-network

  # Selenium test service
  selenium:
    image: selenium/standalone-chrome:latest
    container_name: connect-aid-selenium
    shm_size: '2gb'
    environment:
      - SE_NODE_MAX_SESSIONS=4
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_VNC_NO_PASSWORD=1
    ports:
      - "${SELENIUM_PORT:-4444}:4444"
      - "${SELENIUM_VNC_PORT:-7900}:7900"
    networks:
      - connect-aid-network
    depends_on:
      - frontend
      - backend

  # Test runner service
  test-runner:
    build:
      context: .
      dockerfile: tests/selenium/Dockerfile
    container_name: connect-aid-test-runner
    environment:
      - SELENIUM_HOST=${SELENIUM_HOST:-selenium}
      - SELENIUM_PORT=${SELENIUM_PORT:-4444}
      - FRONTEND_URL=http://frontend:${FRONTEND_PORT:-5173}
      - BACKEND_URL=http://backend:${BACKEND_PORT:-5000}
      - CI=true
      - TEST_BASE_URL=http://${DOMAIN_NAME:-localhost}:${NGINX_PORT:-80}
    volumes:
      - ./tests:/app/tests
      - /app/node_modules
      - ./test-results:/app/test-results
    networks:
      - connect-aid-network
    depends_on:
      - selenium
      - frontend
      - backend

networks:
  connect-aid-network:
    driver: bridge
